id = "note"
name = "Note"
version = "0.0.1"
schema_version = 1
authors = ["Sameer Narendran <sameer.narendran@gmail.com>"]
description = "Syntax highlighting for notetaker's .note format"
repository = "https://github.com/sameer-n012/notetaker"

[grammars.note]
repository = "https://github.com/sameer-n012/notetaker-ts"
rev = "2ccb3250d2a8c4ed8ca0f22c9189737517bd7707"
